### ISSUE TITLE
Explore auto-generating license info on empty repos

### ISSUE THREAD

**Issue by arowla** [18F/about_yml#22]
Default output from the template is not sufficiently explanatory:

``` yaml
# Licenses that apply to the project and/or its components (required)
# Items by property name pattern:
#   .*:
#     name: Name of the license from the Software Package Data Exchange (SPDX): https://spdx.org/licenses/
#     url: URL for the text of the license
licenses:
  placeholder_label:
```

I can't tell if `placeholder_label` is something I'm supposed to understand in this context, or if it's a sign of something unfinished.

Upon looking at this repo's own `.about.yml`, I see the `licenses` field looks like this:

``` yaml
licenses:
  .about.yml:
    name: CC0
    url: https://github.com/18F/about_yml/blob/master/LICENSE.md
```

It's not clear (at least for basic projects) why we should have to re-specify the name of the repo in order to specify its license.

I'd also vote for this field being auto-generated with CC0 filled in, since I think all 18F projects are under the same license.
